Repository argoproj/argo-helm, pull requests merged in 2021-08, with the labels that each got.

#859 feat(argo-cd): Add sessionAffinity to server service
  charts/argo-cd/Chart.yaml
  charts/argo-cd/templates/argocd-server/service.yaml
  charts/argo-cd/values.yaml
Labels: size/XS

#516 feat(argo-events): Ability to specify custom env variables (eg. debugLogging)
  charts/argo-events/Chart.yaml
  charts/argo-events/templates/eventbus-controller-deployment.yaml
  charts/argo-events/templates/eventsource-controller-deployment.yaml
  charts/argo-events/templates/sensor-controller-deployment.yaml
  charts/argo-events/values.yaml
Labels: argo-events, size/S

#861 fix(argo-cd): Set type of service for gRPC as NodePort.
  charts/argo-cd/Chart.yaml
  charts/argo-cd/templates/argocd-server/alb-grpc-service.yaml
Labels: argo-cd, size/XS

#860 fix(argo-rollouts): Add missing liveness and readiness probe
  charts/argo-rollouts/Chart.yaml
  charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
  charts/argo-rollouts/values.yaml
Labels: argo-rollouts, size/M

#854 feat(argo-workflow): Add pathType value to ingress
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/templates/server/server-ingress.yaml
  charts/argo-workflows/values.yaml
Labels: argo-workflows, size/S

#841 feat(argo-workflows): Add support for extra containers in server & controller deployment
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
  charts/argo-workflows/templates/server/server-deployment.yaml
  charts/argo-workflows/values.yaml
Labels: argo-workflows, size/S

#862 fix(argo-cd): AWS GRPC Service Type
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/argocd-server/alb-grpc-service.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/S

#866 feat(argocd-applicationset): Mount emptDir for /tmp and add extraVolumes support
  charts/argocd-applicationset/Chart.yaml
  charts/argocd-applicationset/README.md
  charts/argocd-applicationset/templates/deployment.yaml
  charts/argocd-applicationset/values.yaml
Labels: size/S, argocd-applicationset

#865 feat(argo-cd): Add support for aggregation clusterroles
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/argocd-aggregate-roles.yaml
  charts/argo-cd/values.yaml
Labels: size/M

#725 fix(argo-cd): Fix (full)nameOverride redis-ha sub-chart
  charts/argo-cd/Chart.yaml
  charts/argo-cd/templates/_helpers.tpl
Labels: argo-cd, size/XS

#477 feat(argo-cd): Add argocd image updater
  charts/argocd-image-updater/.helmignore
  charts/argocd-image-updater/Chart.yaml
  charts/argocd-image-updater/README.md
  charts/argocd-image-updater/README.md.gotmpl
  charts/argocd-image-updater/templates/_helpers.tpl
  charts/argocd-image-updater/templates/configmap.yaml
  charts/argocd-image-updater/templates/deployment.yaml
  charts/argocd-image-updater/templates/rbac.yaml
  charts/argocd-image-updater/templates/serviceaccount.yaml
  charts/argocd-image-updater/values.yaml
Labels: enhancement, argocd-image-updater, size/XL

#831 feat(argo-workflows): Bump appVersion to 3.1.5
  charts/argo-workflows/Chart.yaml
  scripts/lint.sh
Labels: argo-workflows, size/XS

#871 feat(argocd-notifications): Add example for defaultTriggers
  charts/argocd-notifications/Chart.yaml
  charts/argocd-notifications/values.yaml
Labels: size/XS

#875 chore: Convert issue templates to issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: size/L

#872 fix(argocd-notifications): Use correct chart icon url
  charts/argocd-notifications/Chart.yaml
Labels: size/XS

#877 chore: Migrate old probot:stale config to github actions
  .github/stale.yaml
  .github/workflows/stale.yml
Labels: size/M

#881 fix(argo-workflows): Fix typo reported in #876
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/templates/controller/workflow-rb.yaml
  charts/argo-workflows/templates/controller/workflow-role.yaml
  charts/argo-workflows/templates/controller/workflow-sa.yaml
Labels: size/S

#879 feat(argo-workflows): Bump appVersion to 3.1.8
  charts/argo-workflows/Chart.yaml
Labels: argo-workflows, size/XS

#886 fix(argo-cd): Remove ArgoCD repo server entrypoint script from command block and drop --staticassets field
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/argocd-repo-server/deployment.yaml
  charts/argo-cd/templates/argocd-server/deployment.yaml
  charts/argo-cd/values.yaml
Labels: size/S

#885 feat(argocd-applicationset): Bump appVersion to 0.2.0
  charts/argocd-applicationset/Chart.yaml
Labels: size/XS

#888 fix(argo-cd): Update README.md for ArgoCD
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
Labels: size/XS

#887 feat(argocd-applicationset): Upgrade application-set to version 0.2.0
  charts/argocd-applicationset/Chart.yaml
  charts/argocd-applicationset/crds/crd-applicationset.yaml
  charts/argocd-applicationset/values.yaml
Labels: size/XXL

#889 feat(argo-cd): Parameterizing dex ports names due to istio 403 errors
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/dex/service.yaml
  charts/argo-cd/values.yaml
Labels: size/S

#890 feat(argo-cd): Add probes for Dex server >= 2.28.0
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/dex/deployment.yaml
  charts/argo-cd/values.yaml
Labels: size/M

#894 feat(argo-cd): Allow global configuration for pod annotations and labels
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/argocd-application-controller/deployment.yaml
  charts/argo-cd/templates/argocd-repo-server/deployment.yaml
  charts/argo-cd/templates/argocd-server/deployment.yaml
  charts/argo-cd/templates/dex/deployment.yaml
  charts/argo-cd/templates/redis/deployment.yaml
  charts/argo-cd/values.yaml
Labels: size/M

#896 docs(argocd-applicationset): Update README and convert it to helm-docs
  charts/argocd-applicationset/Chart.yaml
  charts/argocd-applicationset/README.md
  charts/argocd-applicationset/README.md.gotmpl
  charts/argocd-applicationset/values.yaml
Labels: size/L

#898 fix(argocd-notifications): Use correct names for ConfigMap and Secret
  charts/argocd-notifications/Chart.yaml
  charts/argocd-notifications/templates/configmap.yaml
  charts/argocd-notifications/templates/secret.yaml
Labels: size/XS

#912 fix(argo-rollouts): Also use 'controller.component' parameter in ServiceMonitor
  charts/argo-rollouts/Chart.yaml
  charts/argo-rollouts/templates/argo-rollouts-service-monitor.yaml
Labels: size/XS
