Repository argoproj/argo-helm, pull requests merged in 2021-07, with the labels that each got.

#823 chore(chart-testing-action): Update components
  .github/workflows/lint-and-test.yml
Labels: size/XS

#797 feat(argo-cd): Add ability to manage GnuPG keys
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/argocd-configs/argocd-gpg-keys-cm.yaml
  charts/argo-cd/templates/argocd-repo-server/deployment.yaml
  charts/argo-cd/templates/argocd-server/deployment.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/M

#822 feat(argo-cd): Add pathType value to ingress
  charts/argo-cd/Chart.yaml
  charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
  charts/argo-cd/templates/argocd-server/ingress.yaml
  charts/argo-cd/values.yaml
Labels: size/S

#812 fix(argo-rollouts): Add ConfigMap read access to support notification-engine
  charts/argo-rollouts/Chart.yaml
  charts/argo-rollouts/templates/argo-rollouts-clusterrole.yaml
  charts/argo-rollouts/templates/argo-rollouts-role.yaml
Labels: argo-rollouts, size/XS

#750 feat!: Improve Pull Request Template & Contributing Guidelines
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  charts/argo-cd/Chart.yaml
  charts/argo-events/Chart.yaml
  charts/argo-rollouts/Chart.yaml
  charts/argo-workflows/Chart.yaml
  charts/argocd-applicationset/Chart.yaml
  charts/argocd-notifications/Chart.yaml
Labels: size/M

#760 feat(argo-cd): Add ability to override API versions
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/_helpers.tpl
  charts/argo-cd/templates/argocd-server/certificate.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/S

#827 fix(argocd-applicationset): Cleanup old CRD installation method
  charts/argocd-applicationset/.helmignore
  charts/argocd-applicationset/Chart.yaml
  charts/argocd-applicationset/README.md
  charts/argocd-applicationset/ci/default-values.yaml
  charts/argocd-applicationset/ci/leader-election-values.yaml
  charts/argocd-applicationset/templates/crds.yaml
  charts/argocd-applicationset/values.yaml
Labels: argocd-applicationset, size/M

#828 fix(argo-cd): Add ServiceAccount for redis
  charts/argo-cd/Chart.yaml
  charts/argo-cd/templates/_helpers.tpl
  charts/argo-cd/templates/redis/deployment.yaml
  charts/argo-cd/templates/redis/serviceaccount.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/M

#830 docs(argo-cd): Upgrading notes for ServiceAccount change in 3.8.1
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
Labels: size/M

#800 feat(argo-cd): Add ability to create network policies
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/argocd-application-controller/networkpolicy.yaml
  charts/argo-cd/templates/argocd-repo-server/networkpolicy.yaml
  charts/argo-cd/templates/argocd-server/networkpolicy.yaml
  charts/argo-cd/templates/dex/networkpolicy.yaml
  charts/argo-cd/templates/networkpolicy-default-deny.yaml
  charts/argo-cd/templates/redis/deployment.yaml
  charts/argo-cd/templates/redis/networkpolicy.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/L

#806 feat(argo-cd): Support AWS ALB Ingress with gRPC
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/argocd-server/alb-grpc-service.yaml
  charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
  charts/argo-cd/templates/argocd-server/ingress.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/M

#833 fix(argo-workflows): Fix controller Role/ClusterRole to work with InstanceID
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
  charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
Labels: size/S

#824 feat(argo-workflows): Multiple workflow namespaces
  CONTRIBUTING.md
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/templates/controller/workflow-rb.yaml
  charts/argo-workflows/templates/controller/workflow-role.yaml
  charts/argo-workflows/templates/controller/workflow-sa.yaml
  charts/argo-workflows/values.yaml
Labels: argo-workflows, size/M

#834 fix(argo-workflows): remove old default init service account
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/README.md
  charts/argo-workflows/values.yaml
Labels: size/S

#837 fix(argo-workflows): pod status pending issue
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/crds/argoproj.io_workflows.yaml
Labels: size/XS

#842 docs: Rename argocd references to argoworkflows in workflow chart
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/values.yaml
Labels: size/S

#844 feat(argo-cd): Bump default version to v2.0.5
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/values.yaml
Labels: size/XS

#846 fix(argo-cd): Deprecate the static assets flag passed to argocd-server
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/templates/argocd-server/deployment.yaml
  charts/argo-cd/values.yaml
Labels: size/S

#847 feat(argo-cd): Bump misc dependencies
  charts/argo-cd/Chart.lock
  charts/argo-cd/Chart.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/S

#849 fix(argo-cd): re-enable not yet deprecated staticassets flag
  charts/argo-cd/Chart.yaml
  charts/argo-cd/values.yaml
Labels: size/XS
