Repository argoproj/argo-helm, pull requests merged in 2021-06, with the labels that each got.

#780 chore: Complete migration CircleCI -> GitHub Actions
  .circleci/config.yml
Labels: size/S

#767 chore: Nominate mbevc1 as an approver
  CODEOWNERS
Labels: size/XS

#726 docs(argo-cd): Dex ServiceMonitor labels, namespace and selector
  charts/argo-cd/Chart.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/XS

#783 feat(argocd-notifications): Add metrics service labels and annotations
  charts/argocd-notifications/Chart.yaml
  charts/argocd-notifications/templates/service-metrics.yaml
  charts/argocd-notifications/values.yaml
Labels: argocd-notifications, size/S

#782 docs(argo-workflows): Add missing value on values.yaml
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/values.yaml
Labels: argo-workflows, documentation, size/S

#787 fix(argo-workflows): Observe 'controller.serviceAccount.create'
  charts/argo-workflows/.helmignore
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/templates/controller/workflow-controller-sa.yaml
Labels: size/XS

#788 feat(argocd-applicationset): Add priorityClassName
  charts/argocd-applicationset/Chart.yaml
  charts/argocd-applicationset/templates/deployment.yaml
  charts/argocd-applicationset/values.yaml
Labels: size/XS

#778 chore(argo-events): Cleanup old CRD hooks
  charts/argo-events/.helmignore
  charts/argo-events/Chart.yaml
  charts/argo-events/README.md
  charts/argo-events/templates/argo-events-cluster-roles.yaml
  charts/argo-events/templates/argo-events-roles.yaml
  charts/argo-events/templates/eventbus-crd.yaml
  charts/argo-events/templates/eventsource-crd.yaml
  charts/argo-events/templates/sensor-crd.yaml
  charts/argo-events/values.yaml
Labels: argo-events, size/L

#777 chore(argo-cd): Cleanup old CRD hooks
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/crds/crd-application.yaml
  charts/argo-cd/crds/crd-project.yaml
  charts/argo-cd/templates/crds.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/S

#793 fix(argo-cd): Server cert-manager certificate secretName to match documentation
  charts/argo-cd/Chart.yaml
  charts/argo-cd/templates/argocd-server/certificate.yaml
  charts/argo-cd/values.yaml
Labels: argo-cd, size/XS

#795 fix(argo-workflows): use template for ingress .Capabilities
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/templates/_helpers.tpl
  charts/argo-workflows/templates/server/server-ingress.yaml
  charts/argo-workflows/values.yaml
Labels: argo-workflows, size/S

#796 chore: Relax 'Semantic Pull Requests' check
  .github/semantic.yml
Labels: size/XS

#810 fix(argo-cd): fix missing colon in example service definitions
  charts/argo-cd/Chart.yaml
  charts/argo-cd/values.yaml
Labels: size/XS

#811 chore(argo-workflows): update workflows version to most 3.0.7
  charts/argo-workflows/Chart.yaml
  charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
  charts/argo-workflows/values.yaml
Labels: size/S

#815 fix(argo-cd): Typo in repo server service monitor
  charts/argo-cd/Chart.yaml
  charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
Labels: size/XS

#817 chore: Fix CODEOWNERS syntax
  CODEOWNERS
Labels: size/XS

#816 feat(argo-cd): Bump default version to v2.0.4
  charts/argo-cd/Chart.yaml
  charts/argo-cd/README.md
  charts/argo-cd/values.yaml
Labels: size/XS
